# Generated by scripts/generate-integrations.py; do not edit directly.
set -l color00 '#FFF9E8'
set -l color01 '#AF5860'
set -l color02 '#3F713A'
set -l color03 '#7A5000'
set -l color04 '#8A5A00'
set -l color05 '#80608D'
set -l color06 '#176C68'
set -l color07 '#7D6D48'
set -l color08 '#665A3E'

# Preserve quoted user options; replace only the suffix added by this integration.
if set -q __mooni_fzf_suffix
    set -gx FZF_DEFAULT_OPTS (string replace -- "$__mooni_fzf_suffix" '' "$FZF_DEFAULT_OPTS")
end
set -g __mooni_fzf_suffix " --color=bg+:#F7E5AB,bg:$color00,spinner:$color06,hl:$color04 --color=fg:#302713,header:$color04,info:$color02,pointer:$color06 --color=marker:$color06,fg+:#302713,prompt:$color02,hl+:$color04"
set -gx FZF_DEFAULT_OPTS "$FZF_DEFAULT_OPTS$__mooni_fzf_suffix"
