# Generated by scripts/generate-integrations.py; do not edit directly.
set -l color00 '#FFF9E8'
set -l color01 '#AF5860'
set -l color02 '#5B7B4C'
set -l color03 '#A46B00'
set -l color04 '#8A5A00'
set -l color05 '#80608D'
set -l color06 '#487D7A'
set -l color07 '#7D6D48'
set -l color08 '#665A3E'

set -l non_color_opts
for arg in (string split ' ' -- $FZF_DEFAULT_OPTS)
    if not string match -q -- '--color*' $arg
        set -a non_color_opts $arg
    end
end

set -Ux FZF_DEFAULT_OPTS "$non_color_opts --color=bg+:$color00,bg:$color00,spinner:$color06,hl:$color04 --color=fg:$color07,header:$color04,info:$color02,pointer:$color06 --color=marker:$color06,fg+:$color07,prompt:$color02,hl+:$color04"
