#!/usr/bin/env python3
"""Render Mooni's optional app integrations from the canonical palette."""

import argparse
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PALETTE_PATH = ROOT / "colors.toml"
OUTPUT_DIR = ROOT / "integrations"

TEMPLATES = {
    "bat.conf": """# Generated by scripts/generate-integrations.py; do not edit directly.
# Copy or merge into ~/.config/bat/config. ANSI follows the Omarchy terminal palette.
--theme="ansi"
--style="numbers,changes,header,grid"
--italic-text=always
""",
    "cava-theme": """# Generated by scripts/generate-integrations.py; do not edit directly.
[color]
gradient = 1
gradient_count = 8
gradient_color_1 = '{{ accent }}'
gradient_color_2 = '{{ cyan }}'
gradient_color_3 = '{{ green }}'
gradient_color_4 = '{{ bright_yellow }}'
gradient_color_5 = '{{ orange }}'
gradient_color_6 = '{{ magenta }}'
gradient_color_7 = '{{ cyan }}'
gradient_color_8 = '{{ accent }}'
""",
    "delta.gitconfig": """# Generated by scripts/generate-integrations.py; do not edit directly.
# Include this file from ~/.gitconfig instead of replacing Git settings.

[delta]
    features = mooni

[delta "mooni"]
    syntax-theme = ansi
    plus-style = syntax "{{ green }}"
    minus-style = syntax "{{ red }}"
    zero-style = syntax "{{ muted }}"
    file-style = "{{ accent }}" bold
    hunk-header-style = "{{ cyan }}" italic
    line-numbers = true
    line-numbers-minus-style = "{{ red }}"
    line-numbers-plus-style = "{{ green }}"
""",
    "fastfetch.jsonc": """{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "logo": {
    "type": "small",
    "color": {
      "1": "{{ accent }}",
      "2": "{{ cyan }}",
      "3": "{{ green }}"
    }
  },
  "display": {
    "separator": "  "
  },
  "modules": [
    "title",
    "separator",
    "os",
    "kernel",
    "uptime",
    "packages",
    "shell",
    "wm",
    "terminal",
    "cpu",
    "memory",
    "break"
  ]
}
""",
    "fzf.fish": """# Generated by scripts/generate-integrations.py; do not edit directly.
set -l color00 '{{ background }}'
set -l color01 '{{ red }}'
set -l color02 '{{ green }}'
set -l color03 '{{ yellow }}'
set -l color04 '{{ accent }}'
set -l color05 '{{ magenta }}'
set -l color06 '{{ cyan }}'
set -l color07 '{{ light_foreground }}'
set -l color08 '{{ muted }}'

set -l non_color_opts
for arg in (string split ' ' -- $FZF_DEFAULT_OPTS)
    if not string match -q -- '--color*' $arg
        set -a non_color_opts $arg
    end
end

set -Ux FZF_DEFAULT_OPTS "$non_color_opts --color=bg+:$color00,bg:$color00,spinner:$color06,hl:$color04 --color=fg:$color07,header:$color04,info:$color02,pointer:$color06 --color=marker:$color06,fg+:$color07,prompt:$color02,hl+:$color04"
""",
    "lazygit.yml": """# Generated by scripts/generate-integrations.py; do not edit directly.
# Merge the gui.theme block into ~/.config/lazygit/config.yml.
gui:
  theme:
    activeBorderColor:
      - '{{ accent }}'
      - bold
    inactiveBorderColor:
      - '{{ muted }}'
    searchingActiveBorderColor:
      - '{{ cyan }}'
      - bold
    optionsTextColor:
      - '{{ accent }}'
    selectedLineBgColor:
      - '{{ selection }}'
    selectedRangeBgColor:
      - '{{ darker_background }}'
    cherryPickedCommitBgColor:
      - '{{ darker_background }}'
    cherryPickedCommitFgColor:
      - '{{ foreground }}'
    unstagedChangesColor:
      - '{{ red }}'
    defaultFgColor:
      - '{{ foreground }}'
""",
    "steam.css": """/* Generated by scripts/generate-integrations.py; do not edit directly. */
:root {
    --adw-accent-bg-rgb: {{ accent_rgb }} !important;
    --adw-accent-fg-rgb: {{ background_rgb }} !important;
    --adw-accent-rgb: {{ accent_rgb }} !important;
    --adw-destructive-bg-rgb: {{ red_rgb }} !important;
    --adw-destructive-fg-rgb: {{ background_rgb }} !important;
    --adw-success-bg-rgb: {{ green_rgb }} !important;
    --adw-success-fg-rgb: {{ background_rgb }} !important;
    --adw-warning-bg-rgb: {{ yellow_rgb }} !important;
    --adw-warning-fg-rgb: {{ background_rgb }} !important;
    --adw-window-bg-rgb: {{ background_rgb }} !important;
    --adw-window-fg-rgb: {{ foreground_rgb }} !important;
    --adw-view-bg-rgb: {{ background_rgb }} !important;
    --adw-view-fg-rgb: {{ foreground_rgb }} !important;
    --adw-headerbar-bg-rgb: {{ dark_background_rgb }} !important;
    --adw-headerbar-fg-rgb: {{ foreground_rgb }} !important;
    --adw-headerbar-border-rgb: {{ darker_background_rgb }} !important;
    --adw-sidebar-bg-rgb: {{ dark_background_rgb }} !important;
    --adw-sidebar-fg-rgb: {{ foreground_rgb }} !important;
    --adw-card-bg-rgb: {{ lighter_background_rgb }} !important;
    --adw-card-fg-rgb: {{ foreground_rgb }} !important;
    --adw-dialog-bg-rgb: {{ background_rgb }} !important;
    --adw-dialog-fg-rgb: {{ foreground_rgb }} !important;
    --adw-popover-bg-rgb: {{ lighter_background_rgb }} !important;
    --adw-popover-fg-rgb: {{ foreground_rgb }} !important;
}
""",
    "superfile.toml": """# Generated by scripts/generate-integrations.py; do not edit directly.
file_panel_border = '{{ muted }}'
sidebar_border = '{{ muted }}'
footer_border = '{{ muted }}'

file_panel_border_active = '{{ accent }}'
sidebar_border_active = '{{ accent }}'
footer_border_active = '{{ accent }}'
modal_border_active = '{{ accent }}'

full_screen_bg = '{{ background }}'
file_panel_bg = '{{ background }}'
sidebar_bg = '{{ background }}'
footer_bg = '{{ dark_background }}'
modal_bg = '{{ background }}'

full_screen_fg = '{{ foreground }}'
file_panel_fg = '{{ foreground }}'
sidebar_fg = '{{ foreground }}'
footer_fg = '{{ foreground }}'
modal_fg = '{{ foreground }}'

cursor = '{{ foreground }}'
correct = '{{ green }}'
error = '{{ red }}'
hint = '{{ cyan }}'
cancel = '{{ red }}'
gradient_color = ['{{ selection }}', '{{ accent }}']

file_panel_top_path = '{{ muted }}'
sidebar_title = '{{ foreground }}'
sidebar_item_selected_fg = '{{ accent }}'
sidebar_divider = '{{ muted }}'
""",
    "vencord.theme.css": """/**
 * @name Omarchy Mooni
 * @description Honey-yellow palette for Vencord and Discord.
 * Generated by scripts/generate-integrations.py; do not edit directly.
 */

:root {
    --mooni-bg: {{ background }};
    --mooni-surface: {{ dark_background }};
    --mooni-border: {{ darker_background }};
    --mooni-text: {{ foreground }};
    --mooni-muted: {{ muted }};
    --mooni-accent: {{ accent }};
    --mooni-success: {{ green }};
    --mooni-danger: {{ red }};
}

.theme-light, .theme-dark, .theme-darker, .theme-midnight, .visual-refresh {
    --background-primary: var(--mooni-bg) !important;
    --background-secondary: var(--mooni-surface) !important;
    --background-secondary-alt: var(--mooni-surface) !important;
    --background-tertiary: var(--mooni-border) !important;
    --background-floating: var(--mooni-bg) !important;
    --background-modifier-hover: color-mix(in srgb, var(--mooni-accent) 10%, var(--mooni-bg)) !important;
    --background-modifier-selected: color-mix(in srgb, var(--mooni-accent) 16%, var(--mooni-bg)) !important;
    --channeltextarea-background: var(--mooni-surface) !important;
    --text-normal: var(--mooni-text) !important;
    --text-muted: var(--mooni-muted) !important;
    --channels-default: var(--mooni-muted) !important;
    --interactive-normal: var(--mooni-text) !important;
    --interactive-hover: var(--mooni-accent) !important;
    --interactive-active: var(--mooni-accent) !important;
    --brand-500: var(--mooni-accent) !important;
    --control-brand-foreground: var(--mooni-accent) !important;
    --status-positive: var(--mooni-success) !important;
    --status-danger: var(--mooni-danger) !important;
}
""",
    "yazi-theme.toml": """# Generated by scripts/generate-integrations.py; do not edit directly.
# Merge into ~/.config/yazi/theme.toml; it deliberately avoids layout settings.

[manager]
cwd = { fg = "{{ accent }}" }
hovered = { fg = "{{ background }}", bg = "{{ accent }}" }
preview_hovered = { underline = true }
find_keyword = { fg = "{{ yellow }}", italic = true }
find_position = { fg = "{{ magenta }}", bg = "reset", italic = true }
marker_selected = { fg = "{{ green }}", bg = "{{ green }}" }
marker_copied = { fg = "{{ cyan }}", bg = "{{ cyan }}" }
marker_cut = { fg = "{{ red }}", bg = "{{ red }}" }
tab_active = { fg = "{{ foreground }}", bg = "{{ dark_background }}" }
tab_inactive = { fg = "{{ muted }}", bg = "{{ background }}" }
border_symbol = "│"
border_style = { fg = "{{ darker_background }}" }

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "{{ dark_background }}", bg = "{{ dark_background }}" }
mode_normal = { fg = "{{ background }}", bg = "{{ accent }}", bold = true }
mode_select = { fg = "{{ background }}", bg = "{{ green }}", bold = true }
mode_unset = { fg = "{{ background }}", bg = "{{ yellow }}", bold = true }
progress_label = { fg = "{{ foreground }}", bold = true }
progress_normal = { fg = "{{ accent }}", bg = "{{ darker_background }}" }
progress_error = { fg = "{{ red }}", bg = "{{ darker_background }}" }

[input]
border = { fg = "{{ accent }}" }
title = { fg = "{{ foreground }}" }
value = { fg = "{{ foreground }}" }
selected = { reversed = true }

[select]
border = { fg = "{{ accent }}" }
active = { fg = "{{ background }}", bg = "{{ accent }}" }
inactive = { fg = "{{ foreground }}" }

[which]
mask = { bg = "{{ background }}" }
cand = { fg = "{{ accent }}" }
rest = { fg = "{{ muted }}" }
desc = { fg = "{{ foreground }}" }
separator = "  "
separator_style = { fg = "{{ muted }}" }
""",
    "zed.json": """{
  "$schema": "https://zed.dev/schema/themes/v0.1.0.json",
  "name": "Omarchy Mooni",
  "author": "Pedro Augusto",
  "themes": [
    {
      "name": "Omarchy Mooni",
      "appearance": "light",
      "style": {
        "background": "{{ background }}",
        "editor.background": "{{ background }}",
        "editor.foreground": "{{ foreground }}",
        "text": "{{ foreground }}",
        "text.muted": "{{ muted }}",
        "text.placeholder": "{{ muted }}",
        "border": "{{ darker_background }}",
        "panel.background": "{{ dark_background }}",
        "title_bar.background": "{{ background }}",
        "status_bar.background": "{{ dark_background }}",
        "tab.active_background": "{{ selection }}",
        "element.hover": "{{ selection }}",
        "element.selected": "{{ selection }}",
        "editor.active_line.background": "{{ dark_background }}",
        "editor.gutter.background": "{{ background }}",
        "scrollbar.thumb.background": "{{ muted }}",
        "terminal.background": "{{ background }}",
        "terminal.foreground": "{{ foreground }}",
        "terminal.ansi.black": "{{ background }}",
        "terminal.ansi.red": "{{ red }}",
        "terminal.ansi.green": "{{ green }}",
        "terminal.ansi.yellow": "{{ yellow }}",
        "terminal.ansi.blue": "{{ blue }}",
        "terminal.ansi.magenta": "{{ magenta }}",
        "terminal.ansi.cyan": "{{ cyan }}",
        "terminal.ansi.white": "{{ light_foreground }}",
        "terminal.ansi.bright_black": "{{ muted }}",
        "terminal.ansi.bright_red": "{{ bright_red }}",
        "terminal.ansi.bright_green": "{{ bright_green }}",
        "terminal.ansi.bright_yellow": "{{ bright_yellow }}",
        "terminal.ansi.bright_blue": "{{ bright_blue }}",
        "terminal.ansi.bright_magenta": "{{ bright_magenta }}",
        "terminal.ansi.bright_cyan": "{{ bright_cyan }}",
        "terminal.ansi.bright_white": "{{ bright_foreground }}",
        "syntax.comment": "{{ muted }}",
        "syntax.keyword": "{{ accent }}",
        "syntax.function": "{{ blue }}",
        "syntax.string": "{{ green }}",
        "syntax.number": "{{ orange }}",
        "syntax.type": "{{ yellow }}",
        "syntax.operator": "{{ cyan }}"
      }
    }
  ]
}
""",
}

TOKEN = re.compile(r"\{\{ ([a-z_]+) \}\}")


def rgb(value: str) -> str:
    return ", ".join(str(int(value[index : index + 2], 16)) for index in (1, 3, 5))


def context() -> dict[str, str]:
    palette = tomllib.loads(PALETTE_PATH.read_text())
    colors = {key: value for key, value in palette.items() if key != "mode"}
    values = dict(colors)
    values.update({f"{key}_rgb": rgb(value) for key, value in colors.items()})
    return values


def render(template: str, values: dict[str, str]) -> str:
    def replace(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in values:
            raise ValueError(f"unknown palette token: {key}")
        return values[key]

    return TOKEN.sub(replace, template)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    values = context()
    stale = []
    for filename, template in TEMPLATES.items():
        path = OUTPUT_DIR / filename
        content = render(template, values)
        if args.check:
            if not path.is_file() or path.read_text() != content:
                stale.append(filename)
        else:
            path.write_text(content)

    if stale:
        print(f"Stale generated integrations: {', '.join(stale)}", file=sys.stderr)
        raise SystemExit(1)

    if not args.check:
        print(f"Generated {len(TEMPLATES)} optional integrations.")


if __name__ == "__main__":
    main()
